export const PAYMENT_CURRENCIES = [
	{ value: 'USD', label: 'U.S. Dollar (USD $)' },
	{ value: 'AUD', label: 'Australian Dollar (AUD $)' },
	{ value: 'BDT', label: 'Bangladeshi Taka (BDT ৳)' },
	{ value: 'BRL', label: 'Brazilian Real (BRL R$)' },
	{ value: 'BGN', label: 'Bulgarian Lev (BGN лв)' },
	{ value: 'CAD', label: 'Canadian Dollar (CAD $)' },
	{ value: 'XAF', label: 'Central African CFA Franc (XAF F.CFA)' },
	{ value: 'CRC', label: 'Costa Rican Colón (CRC ₡)' },
	{ value: 'CZK', label: 'Czech Koruna (CZK Kč)' },
	{ value: 'DKK', label: 'Danish Krone (DKK kr.)' },
	{ value: 'EUR', label: 'Euro (EUR €)' },
	{ value: 'HKD', label: 'Hong Kong Dollar (HKD $)' },
	{ value: 'HUF', label: 'Hungarian Forint (HUF Ft)' },
	{ value: 'INR', label: 'Indian Rupee (INR ₹)' },
	{ value: 'ILS', label: 'Israeli New Sheqel (ILS ₪)' },
	{ value: 'JPY', label: 'Japanese Yen (JPY ¥)' },
	{ value: 'MYR', label: 'Malaysian Ringgit (MYR RM)' },
	{ value: 'MXN', label: 'Mexican Peso (MXN $)' },
	{ value: 'NZD', label: 'New Zealand Dollar (NZD $)' },
	{ value: 'NOK', label: 'Norwegian Krone (NOK Kr)' },
	{ value: 'PHP', label: 'Philippine Peso (PHP Php)' },
	{ value: 'PLN', label: 'Polish Zloty (PLN zł)' },
	{ value: 'GBP', label: 'Pound Sterling (GBP £)' },
	{ value: 'RON', label: 'Romanian Leu (RON lei)' },
	{ value: 'RUB', label: 'Russian Ruble (RUB руб)' },
	{ value: 'SAR', label: 'Saudi Arabian Riyal (SAR ر.س)' },
	{ value: 'RSD', label: 'Serbian Dinar (RSD din.)' },
	{ value: 'SGD', label: 'Singapore Dollar (SGD $)' },
	{ value: 'ZAR', label: 'South African Rand (ZAR R)' },
	{ value: 'KRW', label: 'South Korean Won (KRW ₩)' },
	{ value: 'LKR', label: 'Sri Lankan Rupee (LKR Rs)' },
	{ value: 'SEK', label: 'Swedish Krona (SEK Kr)' },
	{ value: 'CHF', label: 'Swiss Franc (CHF CHF)' },
	{ value: 'TWD', label: 'Taiwan New Dollar (TWD $)' },
	{ value: 'THB', label: 'Thai Baht (THB ฿)' },
	{ value: 'TRY', label: 'Turkish Lira (TRY ₺)' },
	{ value: 'AED', label: 'United Arab Emirates Dirham (AED د.إ)' },
];

export const CURRENCY_SIGN_POSITIONS = [
	{ value: 'left', label: 'Left ($100)' },
	{ value: 'right', label: 'Right (100$)' },
	{ value: 'left_space', label: 'Left Space ($ 100)' },
	{ value: 'right_space', label: 'Right Space (100 $)' },
];
