<?php
/**
 * Import forms settings module (UI).
 *
 * @since 2.1.0
 * @package Gutena Forms
 */

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'Gutena_Forms_Import' ) && class_exists( 'Gutena_Forms_Forms_Settings' ) ) :
	/**
	 * Admin settings module for importing Gutena Forms.
	 *
	 * @since 2.1.0
	 */
	class Gutena_Forms_Import extends Gutena_Forms_Forms_Settings {
		/**
		 * Register the import module with the gutena_forms__settings filter.
		 *
		 * @since 2.1.0
		 */
		public static function register_module() {
			add_filter(
				'gutena_forms__settings',
				function ( $settings ) {
					$settings['import'] = __CLASS__;
					return $settings;
				}
			);

			include_once plugin_dir_path( __FILE__ ) . 'class-import-endpoints.php';
		}

		/**
		 * Get settings definition for the import screen template.
		 *
		 * @since 2.1.0
		 * @return array
		 */
		public function get_settings() {
			return array(
				'title'       => __( 'Import Gutena Forms', 'gutena-forms' ),
				'description' => __( 'Import forms exported from another Gutena Forms site using an exported .json file. Only export files generated by Gutena Forms are supported.', 'gutena-forms' ),
				'fields'      => array(
					array(
						'type' => 'template',
						'name' => 'import',
					),
				),
			);
		}

		/**
		 * Save settings (no-op for import module).
		 *
		 * @since 2.1.0
		 * @param array $settings Settings array. Unused.
		 * @return bool
		 */
		public function save_settings( $settings ) {
			return true;
		}
	}

	Gutena_Forms_Import::register_module();
endif;
